### ISSUE TITLE
Reveal button for longmcq()

### ISSUE THREAD

**Issue by philmcaleer** [PsyTeachR/webexercises#8]
**low priority:** Wondering if it would be possible to have a method of not showing the correct or wrong answers to a series of `longmcq()` questions until the student presses a reveal answer type button. So instead of instantly revealing whether the option they chose was correct - by changing to red or green as they go along - the student instead answers a few questions and then presses a reveal button that then changes all the selected answers to red or green at that point. Just thinking it might improve learning and prevent people from just clicking through all options until it goes green and would encourage more thinking.  Would probably be most useful for end of chapter question sets more than anything.

**Comment by dalejbarr** [comment]
Yes, this idea about deferring feedback would be a really nice enhancement, and would also allow for questions where there are multiple correct answers, as requested in this pull request (#9). We will definitely look into this for the next release.

**Comment by debruine** [comment]
See new .webex-check fenced checking sections

**Comment by stefanocoretta** [comment]
Sorry to comment on the closed issue, but as far as I can see, `.webex-check` does not consider multiple answers and it is still not possible to select multiple answers in `longmcq()`. Is there a way to implement this?
